mem0:
  llm:
    provider: openai
    model: google/gemini-3-pro-preview
    api_key: ${ELIZA_API_KEY}
    openrouter_base_url: "https://api.eliza.yandex.net/raw/openrouter/v1"

  embedder:
    provider: openai
    model: text-embedding-3-large
    api_key: ${ELIZA_API_KEY}
    openai_base_url: "https://api.eliza.yandex.net/raw/openai/v1"

  vector_db:
    provider: qdrant
    collection_name: benchmark_books_recommendations
    path: ./qdrant_data
    embedding_model_dims: 3072

  benchmark:
    user_id: benchmark_recommendations
    infer: false
    retrieve_limit: 5

mem_agent:
  model: google/gemini-3-pro-preview
  memory_path: memory_mem_agent/gemini-3-pro
  use_vllm: false
  api_key: ${ELIZA_API_KEY}

benchmark:
  cases:
    - data_path: data/movies_data/movies_data_200.json
      prompt_path: prompts/system_prompt.txt
    - data_path: data/movies_data/movies_data_275.json
      prompt_path: prompts/system_prompt.txt
  output_dir: eval_results/gemini-3-pro
  verbose: false
